### ISSUE TITLE
Support the CONSUMPTION_REQUEST in-app purchase event

### ISSUE THREAD

**Issue by oleksandr-roskovynskyi** [imdhemy/appstore-iap#15]
**Is your feature request related to a problem? Please describe.**
Now not supported this new event

**Describe the solution you'd like**
[notification_type](https://developer.apple.com/documentation/appstoreservernotifications/notification_type
)

**Describe alternatives you've considered**
-
**Additional context**
CONSUMPTION_REQUEST
Indicates that the customer initiated a refund request for a consumable in-app purchase, and the App Store is requesting that you provide consumption data. For more information, see Send Consumption Information.

**Comment by imdhemy** [comment]
This is a question for @oleksandr-roskovynskyi and for any developer interested in this enhancement:

Should we add implementation for [send consumption information](https://developer.apple.com/documentation/appstoreserverapi/send_consumption_information?changes=latest_minor) as well?
