### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by guoshuai-code** [imdhemy/appstore-iap#160]
### Description

1  how to use App Store Server Notifications V2?
2 how to use responseBodyV2DecodedPayload??

Thank you for your reply

**Comment by imdhemy** [comment]
You can have a look on the documentation. Please, let me know if something is missing.

https://imdhemy.com/laravel-iap-docs/

**Comment by ajGulati05** [comment]
Hey the documentation feels pretty sparse. 

]

1. User purhcases on mobile - sends the receipt to server. Server validates it froms apple server?
2. Now the next events apple always sends a notifictaion to the server - for all events


But the above is not clear. Do you have clear examples ? For test notification do you have clear examples on that?

**Comment by imdhemy** [comment]
Here you go:
- https://imdhemy.com/laravel-iap-docs/docs/app-store/sell-subscriptions
- https://imdhemy.com/laravel-iap-docs/docs/get-started/event-listeners
