### ISSUE TITLE
 Imdhemy\AppStore\ValueObjects\LatestReceiptInfo::fromArray(): Argument #1 ($attributes) must be of type array, string given

### ISSUE THREAD

**Issue by fusionconsulting** [imdhemy/appstore-iap#166]
### Package version(s) affected

1.8.2

### Description

I've been using this package for a while and it's been great, but suddenly I've started seeing this error:

Imdhemy\AppStore\ValueObjects\LatestReceiptInfo::fromArray(): Argument #1 ($attributes) must be of type array, string given,  called in /var/www/vendor/imdhemy/appstore-iap/src/Receipts/ReceiptResponse.php on line 166

It seems that $this->latestReceiptInfo should be an array of arrays but is just an array of strings. 

What would cause this to suddenly happen? There have been no updates to the project in question for a while.

### How to reproduce

This is happening for every receipt. It happens on a simple example from the documentation:

        $receiptResponse = Subscription::appStore()->receiptData($receipt)->verifyReceipt();

        $receiptStatus = $receiptResponse->getStatus();

        if( $receiptStatus->isValid() ) {
            $latestReceiptInfo = $receiptResponse->getLatestReceiptInfo();

            dd($latestReceiptInfo);
        }

The dd() is never reached and the contents of $this->latestReceiptInfo in ReceiptResponse.php is:

```
array:25 [
  "original_purchase_date_pst" => "2023-09-10 17:35:23 America/Los_Angeles"
  "quantity" => "1"
  "unique_vendor_identifier" => "<redacted>"
  "bvrs" => "33"
  "expires_date_formatted" => "2023-09-18 00:35:23 Etc/GMT"
  "is_in_intro_offer_period" => "false"
  "purchase_date_ms" => "1694392523000"
  "expires_date_formatted_pst" => "2023-09-17 17:35:23 America/Los_Angeles"
  "is_trial_period" => "true"
  "item_id" => "1436037032"
  "unique_identifier" => "00008110-001A18341E2A401E"
  "original_transaction_id" => "300001567275928"
  "subscription_group_identifier" => "20475442"
  "app_item_id" => "1421810571"
  "transaction_id" => "300001567275928"
  "in_app_ownership_type" => "PURCHASED"
  "web_order_line_item_id" => "300000735476870"
  "version_external_identifier" => "856990522"
  "purchase_date" => "2023-09-11 00:35:23 Etc/GMT"
  "product_id" => "<redacted>"
  "expires_date" => "1694997323000"
  "original_purchase_date" => "2023-09-11 00:35:23 Etc/GMT"
  "purchase_date_pst" => "2023-09-10 17:35:23 America/Los_Angeles"
  "bid" => "<redacted>"
  "original_purchase_date_ms" => "1694392523000"
]
```

### Possible Solution

It looks to me like $this->latestReceiptInfo should be wrapped in an outer array but that was always the case until recently.

**Comment by imdhemy** [comment]
Thanks for reporting the issue.

It could happen because of a change in the response from AppStore. Will have a look on it.

Does it happen in notifications? if yes which version do you use? `v1` or `v2` ?

**Comment by fusionconsulting** [comment]
Thanks. We are not using notifications on this project so I'm not sure if it's happening there. If there's any more information I can get please let me know.

**Comment by imdhemy** [comment]
@fusionconsulting 
Looks like that I miss something. 

- What is the source of the array that you added in the issue description?
- Could you please show me the output of `$receiptResponse->toArray();`

**Comment by fusionconsulting** [comment]
The array in the description is the contents of $this->latestReceiptInfo which I believe should be wrapped in an outer array.

This is the output of `$receiptResponse->toArray()`:
```
    array:7 [
  "expiration_intent" => "1"
  "auto_renew_product_id" => "uk.co.makeyourmindup.ios.monthly"
  "is_in_billing_retry_period" => "1"
  "latest_expired_receipt_info" => array:25 [
    "original_purchase_date_pst" => "2023-09-10 17:35:23 America/Los_Angeles"
    "quantity" => "1"
    "unique_vendor_identifier" => "934D85F9-E667-4CF5-90AA-DE9EA0B14384"
    "bvrs" => "33"
    "expires_date_formatted" => "2023-09-18 00:35:23 Etc/GMT"
    "is_in_intro_offer_period" => "false"
    "purchase_date_ms" => "1694392523000"
    "expires_date_formatted_pst" => "2023-09-17 17:35:23 America/Los_Angeles"
    "is_trial_period" => "true"
    "item_id" => "1436037032"
    "unique_identifier" => "00008110-001A18341E2A401E"
    "original_transaction_id" => "300001567275928"
    "subscription_group_identifier" => "20475442"
    "app_item_id" => "1421810571"
    "transaction_id" => "300001567275928"
    "in_app_ownership_type" => "PURCHASED"
    "web_order_line_item_id" => "300000735476870"
    "version_external_identifier" => "856990522"
    "purchase_date" => "2023-09-11 00:35:23 Etc/GMT"
    "product_id" => "uk.co.makeyourmindup.ios.monthly"
    "expires_date" => "1694997323000"
    "original_purchase_date" => "2023-09-11 00:35:23 Etc/GMT"
    "purchase_date_pst" => "2023-09-10 17:35:23 America/Los_Angeles"
    "bid" => "uk.co.makeyourmindup.makeyourmindup"
    "original_purchase_date_ms" => "1694392523000"
  ]
  "receipt" => array:25 [
    "original_purchase_date_pst" => "2023-09-10 17:35:23 America/Los_Angeles"
    "quantity" => "1"
    "unique_vendor_identifier" => "934D85F9-E667-4CF5-90AA-DE9EA0B14384"
    "bvrs" => "33"
    "expires_date_formatted" => "2023-09-18 00:35:23 Etc/GMT"
    "is_in_intro_offer_period" => "false"
    "purchase_date_ms" => "1694392523000"
    "expires_date_formatted_pst" => "2023-09-17 17:35:23 America/Los_Angeles"
    "is_trial_period" => "true"
    "item_id" => "1436037032"
    "unique_identifier" => "00008110-001A18341E2A401E"
    "original_transaction_id" => "300001567275928"
    "subscription_group_identifier" => "20475442"
    "app_item_id" => "1421810571"
    "transaction_id" => "300001567275928"
    "in_app_ownership_type" => "PURCHASED"
    "web_order_line_item_id" => "300000735476870"
    "version_external_identifier" => "856990522"
    "purchase_date" => "2023-09-11 00:35:23 Etc/GMT"
    "product_id" => "uk.co.makeyourmindup.ios.monthly"
    "expires_date" => "1694997323000"
    "original_purchase_date" => "2023-09-11 00:35:23 Etc/GMT"
    "purchase_date_pst" => "2023-09-10 17:35:23 America/Los_Angeles"
    "bid" => "uk.co.makeyourmindup.makeyourmindup"
    "original_purchase_date_ms" => "1694392523921"
  ]
  "auto_renew_status" => 0
  "status" => 21006
]
```

**Comment by imdhemy** [comment]
This receipt has two interesting data:
## Status
The status value, which is `21006`
> This receipt is valid, but the subscription is in an expired state. When your server receives this status code, the system also decodes and returns receipt data as part of the response. This status only returns for iOS 6-style transaction receipts for auto-renewable subscriptions.

Based on this status value, you need to use `getReceipt()` instead of `getLatestReceiptInfo()`

##  latest_expired_receipt_info
This key is not supported by the package. I don't think I'm going to support it. The current workflow is already deprecated by Apple, and I will invest this time to support the new workflows.

Thank you again for bringing this issue.
